### ISSUE TITLE
Variables not expanded in values

### ISSUE THREAD

**Issue by tjwallace** [direnv/go-dotenv#3]
`.env` file:
```
FOO=test
BAR=$FOO
```

`.envrc` file:
```
dotenv
```

Command: `echo $BAR`
Expected output: `test`
Actual output: `$FOO`

### Links
- [Specs from ruby implementation](https://github.com/bkeepers/dotenv/blob/master/spec/dotenv/parser_spec.rb#L49-L56)

**Comment by zimbatm** [comment]
:+1: [link to ruby implementation](https://github.com/bkeepers/dotenv/blob/84f33f48107c492c3a99bd41c1059e7b4c1bb67a/lib/dotenv/substitutions/variable.rb)

Command substitutions are also missing.

Are you up for implementing it?

**Comment by hakamadare** [comment]
@zimbatm please take a look at my PR when you have a moment, i believe this will provide basic environment variable expansion in dotenv files.  if you accept this, please cut a new release of direnv so that i can more easily use this feature :)
