### ISSUE TITLE
[Feature] Allow specifying default values

### ISSUE THREAD

**Issue by KevinLoganBS** [direnv/go-dotenv#5]
It would be nice to have the ability to allow keeping variables specified outside of direnv, and specifying sane defaults if it's empty/null.

In shell, normally the syntax is `${parameter:-word}`. A more robust, but mostly unnecessary/overly advanced list would be https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html.

Is this something that would be possible, or would this feature not be desired?

**Comment by zimbatm** [comment]
It would be possible if you are up for implementing it.

It would require to:
* change the `Parse` function signature to also take an `env map[string]string` argument so it can fill those variables.
* parse the values one more time like in https://github.com/bkeepers/dotenv/blob/84f33f48107c492c3a99bd41c1059e7b4c1bb67a/lib/dotenv/parser.rb
* add quite a few tests to make sure it works as expected
