### ISSUE TITLE
Inline comment value includes spaces at last until "#"

### ISSUE THREAD

**Issue by sanak** [direnv/go-dotenv#7]
**Describe the bug**
Inline comment seems to be supported, but value includes spaces at last until "#".

**To Reproduce**
When defining key/value with inline comment in `.env` file,
```dotenv
SMTP_ADDRESS=smtp # This is a comment
```
`env` shows <code>SMTP_ADDRESS=smtp&nbsp;</code> (with a space at last).

When adding more spaces (like 4) until "#"  in `.env` file,
```dotenv
SMTP_ADDRESS=smtp    # This is a comment
```
`env` shows <code>SMTP_ADDRESS=smtp&nbsp;&nbsp;&nbsp;&nbsp;</code> (with 4 spaces at last).

**Expected behavior**
Last spaces between value and "#" should be trimmed.

**Environment**
 - OS: macOS Monterey (M1)
 - Shell: zsh
 - Direnv version: 2.31.0 (via homebrew)

**Additional context**
I set `.envrc` file as follows.
```
dotenv
```

**Comment by zimbatm** [comment]
thanks!

**Comment by sanak** [comment]
@zimbatm Wow, thanks for the quick fix! 🙇‍♂️
